# Generated by Django 4.2 on 2024-06-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='Comuna',
            new_name='comuna',
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_de_inmueble',
            field=models.CharField(choices=[('departamento', 'Departamento'), ('casa', 'Casa'), ('oficina', 'Oficina'), ('parcela', 'Parcela')], max_length=12),
        ),
        migrations.AlterField(
            model_name='solicitud_arriendo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('arrendatario', 'Arrendatario'), ('arrendador', 'Arrendador')], max_length=12),
        ),
    ]
