# Generated by Django 4.2 on 2024-06-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_usuario_is_active_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
    ]
